const express = require('express');
const router = express.Router();
const verifyToken = require('../auth/services/verifyToken').verifyToken;
const uurService = require('./service');
router.get("/", verifyToken, uurService.get);
router.post("/list", verifyToken, uurService.get);
router.post("/all", verifyToken, uurService.getAll);
router.get("/all", verifyToken, uurService.getAll);
router.get("/:_id", verifyToken, uurService.getById);
router.post("/", verifyToken, uurService.create);
router.put("/action/:_id", verifyToken, uurService.action);
module.exports = router;