
let arr = [
  {
    key: 'totalRecActual',
    label: 'Total Receipts (Actual)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '20',
    input: 'number'
  },
  {
    key: 'totalRcptWaterSupply',
    label: 'Total Receipts (Actual) for Water Supply',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '21',
    input: 'number'
  },
  {
    key: 'sewerageTax',
    label: 'Sewerage tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.4',
    input: 'number'
  },
  {
    key: 'totalRcptSanitation',
    label: 'Total Receipts (Actual) for Sanitation/Sewerage',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '22',
    input: 'number'
  },
  {
    key: 'RcptBudget',
    label: 'Total Receipts (Budget Estimate)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '23',
    input: 'number'
  },
  {
    key: 'propertyTax',
    label: 'Property Tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.1',
    input: 'number'
  },
  {
    key: 'waterTax',
    label: 'Water tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.2',
    input: 'number'
  },
  {
    key: 'taxRevenue',
    label: 'Tax Revenue',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1',
    input: 'number'
  },
  {
    key: 'drainageTax',
    label: 'Drainage tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.3',
    input: 'number'
  },
  {
    key: 'profTax',
    label: 'Professional tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.5',
    input: 'number'
  },
  {
    key: 'entertainTax',
    label: 'Entertainment tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.6',
    input: 'number'
  },
  {
    key: 'advTax',
    label: 'Advertisement tax',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.7',
    input: 'number'
  },
  {
    key: 'otherTaxRev',
    label: 'All other tax revenues (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '1.8',
    input: 'number'
  },
  {
    key: 'feeUserChrg',
    label: 'Fees & User charges',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '2',
    input: 'number'
  },
  {
    key: 'waterSupplyFee',
    label: 'Fees & user charges from Water supply',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '2.1',
    input: 'number'
  },
  {
    key: 'sanitationFee',
    label: 'Fees & user charges from Sanitation / Sewerage',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '2.2',
    input: 'number'
  },
  {
    key: 'garbageFee',
    label: 'Fees & user charges from Garbage collection / Solid waste management',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '2.3',
    input: 'number'
  },
  {
    key: 'otherFee',
    label: 'All other fees & user charges (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '2.4',
    input: 'number'
  },
  {
    key: 'rentInc',
    label: 'Rental Income from Municipal Properties',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '3',
    input: 'number'
  },
  {
    key: 'assignedCompensation',
    label: 'Assigned Revenues & Compensation',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '4',
    input: 'number'
  },
  {
    key: 'octroiCompensation',
    label: 'Compensation in lieu of Octroi',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '4.1',
    input: 'number'
  },
  {
    key: 'otherCompensation',
    label: 'All other assigned revenues & compensation (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '4.2',
    input: 'number'
  },
  {
    key: 'revGrants',
    label: 'Revenue Grants, Contributions & Subsidies',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5',
    input: 'number'
  },
  {
    key: 'centralGrant',
    label: 'Revenue Grants from Union/Central Government',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.1',
    input: 'number'
  },
  {
    key: 'faLandBuild',
    label: 'Land & Buildings',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '17.1',
    input: 'number'
  },
  {
    key: 'faOther',
    label: 'Other Fixed Assets',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '17.2',
    input: 'number'
  },
  {
    key: 'debtOs',
    label: 'Total Debt outstanding',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '18',
    input: 'number'
  },
  {
    key: 'assetsSale',
    label: 'Income from Sale of Assets',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '19',
    input: 'number'
  },
  {
    key: 'incmLandSale',
    label: 'Income from Sale of Land',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '19.1',
    input: 'number'
  },
  {
    key: 'incmOtherAssets',
    label: 'Income from Sale of Other Assets',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '19.2',
    input: 'number'
  },
  {
    key: 'netRevenue',
    label: 'REVENUE SURPLUS / (DEFICIT) (difference of 7.2 and 14)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '15',
    input: 'number'
  },
  {
    key: 'cfcGrant',
    label: 'Central Finance Commission (CFC) grants',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.11',
    input: 'number'
  },
  {
    key: 'cssGrant',
    label: 'Centrally Sponsored Schemes (CSS) grants',
    codes: [],
    years: [ undefined, '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.12',
    input: 'number'
  },
  {
    key: 'centralscheme',
    label: 'Central sector scheme grants',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.13',
    input: 'number'
  },
  {
    key: 'centralTransfer',
    label: 'Other central transfers (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.14',
    input: 'number'
  },
  {
    key: 'stateGrant',
    label: 'Revenue Grants from State Government',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.2',
    input: 'number'
  },
  {
    key: 'sfcGrant',
    label: 'State Finance Commission (SFC) grants',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.21',
    input: 'number'
  },
  {
    key: 'stateScheme',
    label: 'Transfers under State schemes',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.22',
    input: 'number'
  },
  {
    key: 'otherStateTrans',
    label: 'Other state transfers (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.23',
    input: 'number'
  },
  {
    key: 'otherGrant',
    label: 'All other revenue grants, contributions & subsidies (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '5.3',
    input: 'number'
  },
  {
    key: 'otherIncome',
    label: 'Other income (incl. Sale & Hire charges, Income from Investments, Interest earned, etc.)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '6',
    input: 'number'
  },
  {
    key: 'totalOwnRevenue',
    label: 'TOTAL OWN REVENUE RECEIPTS - ACTUAL (sum of 1 to 3)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '7.1',
    input: 'number'
  },
  {
    key: 'totalIncome',
    label: 'TOTAL REVENUE RECEIPTS – ACTUAL (sum of 1 to 6)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '7.2',
    input: 'number'
  },
  {
    key: 'establishExpense',
    label: 'Establishment Expenses',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '8',
    input: 'number'
  },
  {
    key: 'categoryA',
    label: 'Towards category A',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '8.1',
    input: 'number'
  },
  {
    key: 'categoryB',
    label: 'Towards category B',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '8.2',
    input: 'number'
  },
  {
    key: 'categoryC',
    label: 'Towards category C',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '8.3',
    input: 'number'
  },
  {
    key: 'otherEstExpense',
    label: 'Other establishment expenses (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '8.4',
    input: 'number'
  },
  {
    key: 'adminExpense',
    label: 'Administrative Expenses',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '9',
    input: 'number'
  },
  {
    key: 'fixedAsset',
    label: 'Total Fixed Assets (Gross Block)',
    codes: [ 410 ],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '17',
    input: 'number'
  },
  {
    key: 'CaptExpOther',
    label: 'Other Capital Expenditure (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '16.3',
    input: 'number'
  },
  {
    key: 'totalOmExp',
    label: 'Operations & Maintenance',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '10',
    input: 'number'
  },
  {
    key: 'omExpOther',
    label: 'All other O&M expenses (combined)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '10.3',
    input: 'number'
  },
  {
    key: 'totalCaptlExpWaterSupply',
    label: 'O&M expense on Water Supply',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '10.1',
    input: 'number'
  },
  {
    key: 'totalOMCaptlExpSanitation',
    label: 'O&M expense on Sanitation / Sewerage',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '10.2',
    input: 'number'
  },
  {
    key: 'finExpense',
    label: 'Interest & Finance Expenses',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '11',
    input: 'number'
  },
  {
    key: 'misExpense',
    label: 'Depreciation, Provisions & Write off, Miscellaneous Expenses',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '12',
    input: 'number'
  },
  {
    key: 'otherExpense',
    label: 'Other expenses (incl. Programme Expenses, Revenue Grants, Contributions & Subsidies)',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '13',
    input: 'number'
  },
  {
    key: 'totalExpend',
    label: 'TOTAL REVENUE EXPENDITURE - ACTUAL',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '14',
    input: 'number'
  },
  {
    key: 'CaptlExp',
    label: 'Total Capital Expenditure',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '16',
    input: 'number'
  },
  {
    key: 'CaptlExpWaterSupply',
    label: 'Capital Expenditure for Water Supply',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '16.1',
    input: 'number'
  },
  {
    key: 'CaptlExpSanitation',
    label: 'Capital Expenditure for Sanitation/Sewerage',
    codes: [],
    years: [ '2018-19', '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '16.2',
    input: 'number'
  },
  {
    key: 'auditAnnualReport',
    label: 'Date of Audit Report for audited annual accounts',
    codes: [],
    years: [ '2019-20', '2020-21', '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '24',
    input: 'number'
  },
  {
    key: 'totalOwnRevenueArea',
    label: 'Total Own Revenue Arrears as on 31st March 2022',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '25',
    input: 'number'
  },
  {
    key: 'webUrlAnnual',
    label: 'ULB website URL link where Audited Accounts are available',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '26',
    input: 'number'
  },
  {
    key: 'registerGis',
    label: 'Is the property tax register GIS-based?',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '27',
    input: 'number'
  },
  {
    key: 'registerGisProof',
    label: 'Please upload proof',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '27.1',
    input: 'number'
  },
  {
    key: 'accountStwre',
    label: 'Do you use accounting software? ( Eg.Tally, State-prescribed ERP etc)',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '28',
    input: 'number'
  },
  {
    key: 'accountStwreProof',
    label: 'Please upload proof',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '28.1',
    input: 'number'
  },
  {
    key: 'fy_21_22_cash',
    label: 'Own Revenue collection amount for FY 2021-22 - by Cash/Cheque/DD',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '29',
    input: 'number'
  },
  {
    key: 'fy_21_22_online',
    label: 'Own Revenue collection amount for FY 2021-22 - by Online modes/channels',
    codes: [],
    years: [ '2018-19' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '30',
    input: 'number'
  },
  {
    key: 'property_tax_register',
    label: 'Number of Properties assessed/listed as per Property Tax during FY 2021-22.',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '31',
    input: 'number'
  },
  {
    key: 'paying_property_tax',
    label: 'Number of Properties exempt from paying Property Tax during FY 2021-22.',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '32',
    input: 'number'
  },
  {
    key: 'paid_property_tax',
    label: 'Number of Properties for which Property Tax has been paid during FY 2021-22.',
    codes: [],
    years: [ '2021-22' ],
    formFieldType: 'number',
    required: true,
    displayPriority: '33',
    input: 'number'
  }
]

const FRTypeShortKey = [
  'auditedAnnualFySt',
  'auditAnnualReport',    
  'totalRecActual',
  'totalRcptWaterSupply',
  'sewerageTax',
  'totalRcptSanitation',
  'totalRecBudgetEst',
  'totalOwnRevenue',
  'propertyTax',
  'waterTax',
  'taxRevenue',
  'drainageTax',
  'profTax',
  'entertainTax',
  'advTax',
  'otherTaxRev',
  'feeUserChrg',
  'waterSupplyFee',
  'sanitationFee',
  'garbageFee',
  'otherFee',
  'rentInc',
  'assignedCompensation',
  'octroiCompensation',
  'otherCompensation',
  'revGrants',
  'centralGrant',
  'faLandBuild',
  'faOther',
  'debtOs',
  'assetsSale',
  'incmLandSale',
  'incmOtherAssets',
  'cfcGrant',
  'cssGrant',
  'netRevenue',
  'centralscheme',
  'centralTransfer',
  'stateGrant',
  'sfcGrant',
  'stateScheme',
  'otherStateTrans',
  'otherGrant',
  'otherIncome',
  'totalIncome',
  'establishExpense',
  'categoryA',
  'categoryB',
  'categoryC',
  'otherEstExpense',
  'adminExpense',
  'totalCaptlExp',
  'fixedAsset',
  'CaptExpOther',
  'totalOmExp',
  'omExpOther',
  'grossBeforePrior',
  'totalOMCaptlExpWaterSupply',
  'totalOMCaptlExpSanitation',
  'finExpense',
  'misExpense',
  'otherExpense',
  'totalExpend',
  'grossAfterPrior',
  'priorItems',
  'reservFunds',
  'netBal',
  'OwnRvnue',
  'RvnueExp',
  'CaptlExp',
  'CaptlExpWaterSupply',
  'CaptlExpSanitation',
  'auditAnnualReport',
  'totalOwnRevenueArea',
  'webUrlAnnual',
  'registerGis',
  'registerGisProof',
  'accountStwre',
  'fy_21_22_online',
  'fy_21_22_cash',
  'property_tax_register',
  'paying_property_tax',
  "RcptBudget",
  "totalCaptlExpWaterSupply",
  'paid_property_tax',
  'appAnnualBudget',
  'accountStwreProof'
]
module.exports.FRTypeShortKey = FRTypeShortKey
module.exports.arr = arr;