require("./dbConnect");
const propertyTaxOpMapper = new Schema(
    {
        ptoId: { type: Schema.Types.ObjectId, ref: "PropertyTaxOp", required: true },
        ulb: { type: Schema.Types.ObjectId, ref: "Ulb", required: true },
        year: { type: Schema.Types.ObjectId, ref: "Year", required: true },
        value: { type: Schema.Types.Mixed, default: null },
        date: { type: Date, default: null }, // audit date
        status: {
            type: String,
            default: "PENDING",
            enum: {
                values: ["PENDING", "APPROVED", "REJECTED", "NA"],
                message: "ERROR: STATUS BE EITHER 'PENDING'/ 'APPROVED' / 'REJECTED'",
            },
        },
        isActive: { type: Boolean, default: 1 },
        child:[{
            type: Schema.Types.ObjectId,
            ref:"PropertyMapperChildData"
        }],
        replicaCount:{type:Number},
        type: {
            type: String,
            enum: {
                values: [
                    "notificationPropertyTax",
                    "notificationAdoptionDate",
                    "notificationIssuedBy",
                    "notificationFile",
                    "dmdIncludingCess",
                    "cdmdIncludingCess",
                    "admdIncludingCess",
                    "dmdexcludingCess",
                    "taxTypeDemand",
                    "cessDemand",
                    "doesUserChargesDmnd",
                    "userChargesDmnd",
                    "collectIncludingCess",
                    "cuCollectIncludingCess",
                    "arCollectIncludingCess",
                    "collectExcludingCess",
                    "taxTypeCollection",
                    "cessCollect",
                    "userChargesCollection",
                    "totalMappedPropertiesUlb",
                    "totalPropertiesTax",
                    "totalPropertiesTaxDm",
                    "totalPropertiesTaxDmCollected",
                    "resValuePropertyTaxDm",
                    "resNoPropertyTaxDm",
                    "resValuePropertyTaxCollected",
                    "resNoPropertyTaxCollected",
                    "comValuePropertyTaxDm",
                    "comNoPropertyTaxDm",
                    "comValuePropertyTaxCollected",
                    "comNoPropertyTaxCollected",
                    "indValuePropertyTaxDm",
                    "indNoPropertyTaxDm",
                    "indValuePropertyTaxCollected",
                    "indNoPropertyTaxCollected",
                    "govValuePropertyTaxDm",
                    "govNoPropertyTaxDm",
                    "govValuePropertyTaxCollected",
                    "govNoPropertyTaxCollected",
                    "insValuePropertyTaxDm",
                    "insNoPropertyTaxDm",
                    "insValuePropertyTaxCollected",
                    "insNoPropertyTaxCollected",
                    "otherValuePropertyType",
                    "otherValuePropertyTaxDm",
                    "otherNoPropertyTaxDm",
                    "otherValuePropertyTaxCollected",
                    "otherNoPropertyTaxCollected",
                    "noOfPropertiesPaidOnline",
                    "totalCollectionOnline",
                    "propertyTaxValuationDetails",
                    "notificationWaterCharges",
                    "entityWaterCharges",
                    "entityNameWaterCharges",
                    "notificationWaterChargesFile",
                    "waterChrgDm",
                    "cuWaterChrgDm",
                    "arWaterChrgDm",
                    "waterChrgCol",
                    "cuWaterChrgCol",
                    "arWaterChrgCol",
                    "waterChrgConnectionDm",
                    "waterChrgConnectionCol",
                    "resValueWaterChrgDm",
                    "resNoWaterChrgDm",
                    "resValueWaterChrgCollected",
                    "resNoWaterChrgCollected",
                    "comValueWaterChrgDm",
                    "comNoWaterChrgDm",
                    "comValueWaterChrgCollected",
                    "comNoWaterChrgCollected",
                    "indValueWaterChrgDm",
                    "indNoWaterChrgDm",
                    "indValueWaterChrgCollected",
                    "indNoWaterChrgCollected",
                    "othersValueWaterType",
                    "othersValueWaterChrgDm",
                    "othersNoWaterChrgDm",
                    "othersValueWaterChrgCollected",
                    "othersNoWaterChrgCollected",
                    "waterChrgTariffDetails",
                    "omCostDeleveryWater",
                    "omCostWaterService",
                    "doesColSewerageCharges",
                    "entitySewerageCharges",
                    "entityNaSewerageCharges",
                    "copyGazetteNotificationSewerage",
                    "totalSewergeChrgDm",
                    "curSewergeChrgDm",
                    "arrSewergeChrgDm",
                    "totalSewergeChrgCol",
                    "curSewergeChrgCol",
                    "arrSewergeChrgCol",
                    "totalSewergeConnectionDm",
                    "totalSewergeConnectionCol",
                    "resValueSewerageTaxDm",
                    "resNoSewerageTaxDm",
                    "resValueSewerageTaxCollected",
                    "resNoSewerageTaxCollected",
                    "comValueSewerageTaxDm",
                    "comNoSewerageTaxDm",
                    "comValueSewerageTaxCollected",
                    "comNoSewerageTaxCollected",
                    "indValueSewerageTaxDm",
                    "indNoSewerageTaxDm",
                    "indValueSewerageTaxCollected",
                    "indNoSewerageTaxCollected",
                    "otherValueSewerageType",
                    "otherValueSewerageTaxDm",
                    "otherNoSewerageTaxDm",
                    "otherValueSewerageTaxCollected",
                    "otherNoSewerageTaxCollected",
                    "sewerageChrgTarrifSheet",
                    "omCostDeleverySewerage",
                    "omCostSewerageService",
                    "signedPdf"
                  ],
                message: "ERROR: STATUS BE EITHER",
            },
        },
        file: {
            name: { type: String },
            url: { type: String }
        },
        displayPriority: { type: String, default: null },
    },
    
    { timestamp: { createdAt: "createdAt", updatedAt: "modifiedAt" } }
);
propertyTaxOpMapper.index(
    { ptoId: 1 }
);
module.exports = mongoose.model("PropertyTaxOpMapper", propertyTaxOpMapper);


